Feat/newcomponent cy
https-github-com-tingtinghsu/PMasterProject pull request #9
Opened 2020-08-26 09:08 UTC by ice12031110

Feat/newcomponent cy

2020-08-26 09:12 UTC, Kevinw3i approved these changes
o

2020-08-26 09:26 UTC, XiaoMei-Yeh approved these changes
OK~

2020-08-26 12:28 UTC, XiaoMei-Yeh approved these changes

2020-08-27 12:44 UTC, XiaoMei-Yeh commented on app/frontend/components/icon.vue
> +     <div class="icon"><img :src="src"></div>
coding style 2 spaces

2020-08-27 12:53 UTC, tingtinghsu approved these changes
OK

2020-08-27 12:53 UTC, tingtinghsu commented on app/views/board.html
> +      </div>       <div class="icon"><img src="https://picsum.photos/50/50?random=2"></div>
這裡縮排可以調整一下～

2020-08-27 14:18 UTC, tingtinghsu requested changes
pull這個分支下來跑後，發現首頁出不來

2020-08-27 15:10 UTC, tingtinghsu commented
會另開分支(fix/newcomponent)，修正navbar問題

2020-08-27 15:10 UTC, closed without merging